stages:
  - build
  - test
  - integration_test

workflow:
  rules:
    - when: always

build_wheel:
  stage: build
  tags:
    - internet
  image: python:3.11-bullseye
  script:
    - python setup.py bdist_wheel --universal
  artifacts:
    paths:
      - "dist/*.whl"

test:
  stage: test
  tags:
    - test
    - internet
  parallel:
    matrix:
      - PYTHON_IMAGE_TAG: [2.7-buster, 3.4-stretch, 3.5-buster, 3.11-bullseye]
  image: python:${PYTHON_IMAGE_TAG}
  needs:
    - build_wheel
  before_script:
    - ls ./dist/*.whl | xargs pip install
    - pip install pytest pytest-cov pytest-mock requests-mock vcrpy "jsonschema==2.5.1;python_version=='3.4'" "jsonschema;python_version!='3.4'"
  script:
    - pytest --cov=. --cov-report=xml
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

include:
  - local: ci/common.yml
