stages:
  - build
  - test
  - integration_test

workflow:
  rules:
    - when: always

build_wheel:
  stage: build
  tags:
    - internet
  image: python:3.13-bookworm
  script:
    - pip install build wheel
    - python -m build
  artifacts:
    paths:
      - "dist/*.whl"

.test:
  stage: test
  tags:
    - test
    - internet
  parallel:
    matrix:
      - PYTHON_IMAGE_TAG: [3.10-bullseye, 3.13-bookworm]
  image: python:${PYTHON_IMAGE_TAG}

test:
  extends: .test
  script:
    - pip install '.[test]'
    - pytest --cov=. --cov-report=xml
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml


include:
  - local: ci/common.yml
