stages:
  - build
  - test
  - integration_test

workflow:
  rules:
    - when: always

build_wheel:
  stage: build
  tags:
    - internet
  image: python:3.11-bullseye
  script:
    - pip install build wheel
    - python -m build
  artifacts:
    paths:
      - "dist/*.whl"

.test:
  stage: test
  tags:
    - test
    - internet
  parallel:
    matrix:
      - PYTHON_IMAGE_TAG: [3.7-buster, 3.12-bookworm]
  image: python:${PYTHON_IMAGE_TAG}

test:
  extends: .test
  script:
    - pip install '.[test]'
    - pytest --cov=. --cov-report=xml
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

test_partial_sync:
  extends: .test
  script:
    - pip install .
    - compote registry sync --component example/cmp --component "espressif/mdns<1.1" /tmp/current
    - pip install "idf-component-manager<2"
    - compote registry sync --component example/cmp --component "espressif/mdns<1.1" /tmp/previous
    - diff -r /tmp/current /tmp/previous

include:
  - local: ci/common.yml
